
CREATE TABLE Pessoa 
( 
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nome VARCHAR NOT NULL,  
 cpf CHAR(11),  
 passaporte VARCHAR,  
 email VARCHAR NOT NULL,  
 dt_nascimento DATE,  
 pais CHAR(3) NOT NULL,  
 /* associacao_vigente (calculado) BOOLEAN NOT NULL, */ /* REMOVIDO POIS OS CALCULADOS FICARÃO NO SELECT */
 uf CHAR(2) NOT NULL,  
 
 UNIQUE (cpf),
 UNIQUE (passaporte),
 UNIQUE (email)
); 

CREATE TABLE Evento 
( 
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 ano INT NOT NULL,  
 dt_inicio DATE NOT NULL,  
 dt_fim DATE NOT NULL,  
 modalidade_edicao VARCHAR NOT NULL,  
 nome_lote_1 VARCHAR NOT NULL,  
 dt_inicio_lote_1 DATE NOT NULL,  
 dt_fim_lote_1 DATE NOT NULL,  
 preco_base_lote_1 NUMERIC(16,2) NOT NULL,  /* 16 dígitos totais, sendo dois depois da vírgula para contar os centavos */
 nome_lote_2 VARCHAR,  
 dt_inicio_lote_2 DATE,  
 dt_fim_lote_2 DATE,  
 preco_base_lote_2 NUMERIC(16,2),  
 nome_lote_3 VARCHAR,  
 dt_inicio_lote_3 DATE,  
 dt_fim_lote_3 DATE,  
 preco_base_lote_3 NUMERIC(16,2),  
 nome_lote_4 VARCHAR,  
 dt_inicio_lote_4 DATE,  
 dt_fim_lote_4 DATE,  
 preco_base_lote_4 NUMERIC(16,2),  
 sigla VARCHAR NOT NULL,  
 nome VARCHAR NOT NULL,  
 descricao VARCHAR NOT NULL,  
 cidade VARCHAR NOT NULL,  
 estado CHAR(2) NOT NULL,  
 pais CHAR(3) NOT NULL,  
 edicao VARCHAR NOT NULL,  
 tipo VARCHAR NOT NULL,  
 id_agregado_por INT 
); 

CREATE TABLE Categoria_inscricao 
( 
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 fator_mult_preco NUMERIC(8,7) NOT NULL DEFAULT 1.0,  /* 8 dígitos, 1 antes e 7 depois da vírgula */
 nome VARCHAR NOT NULL,  
 descricao VARCHAR NOT NULL,  
 id_evento INT NOT NULL
); 

CREATE TABLE Inscricao 
( 
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 /* status (calculado) VARCHAR NOT NULL DEFAULT 'PENDENTE',  
 valor_total (calculado) FLOAT NOT NULL DEFAULT '0',  */
 /* dt_confirmacao (calculado) TIMESTAMP, */ 
 dt_inscricao TIMESTAMP NOT NULL,  /* precisei mudar de DATETIME para TIMESTAMP que é o aceito pelo postgres */ 
 id_categoria INT NOT NULL,  
 id_pessoa INT NOT NULL
); 

CREATE TABLE Atividade 
( 
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 preco NUMERIC(16,2) NOT NULL DEFAULT 0.0,  
 dt_inicio TIMESTAMP NOT NULL,  
 dt_fim TIMESTAMP NOT NULL,  
 nome VARCHAR NOT NULL,  
 tipo VARCHAR NOT NULL,  
 id_categoria_inscricao INT NOT NULL
); 

CREATE TABLE Pagamento 
( 
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 valor NUMERIC(16,2) NOT NULL,  
 dt_criacao TIMESTAMP NOT NULL,  
 dt_confirmacao TIMESTAMP,  
 /* status (calculado) VARCHAR NOT NULL DEFAULT 'PENDENTE',  */
 cod_transacao VARCHAR,  
 modalidade VARCHAR NOT NULL,  
 id_reembolsa INT,  
 id_item_financeiro INT NOT NULL,  
 /* status VARCHAR(20) GENERATED ALWAYS AS (
	CASE 
		WHEN dt_confirmacao IS NOT NULL THEN 'CONFIRMADO'
		ELSE 'PENDENTE'
	END
 ) STORED,*/
 
 UNIQUE (cod_transacao),
 UNIQUE (id_reembolsa)
); 

CREATE TABLE Associacao_a_SBTC
( 
  id_pessoa INT NOT NULL,
  dt_inicio DATE NOT NULL,  
  dt_fim DATE NOT NULL,  
  
  PRIMARY KEY (id_pessoa, dt_inicio, dt_fim)
);

CREATE TABLE Item_financeiro 
( 
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 /* dt_pagamento (calculado) TIMESTAMP,  */
 /* valor_pago (calculado) FLOAT NOT NULL DEFAULT '0',  */
 dt_cancelamento TIMESTAMP,
 id_inscricao INT NOT NULL,
 descricao VARCHAR NOT NULL,
 valor NUMERIC(16,2) NOT NULL,
 tipo VARCHAR NOT NULL
 /* status VARCHAR(20) GENERATED ALWAYS AS (
	CASE
		WHEN dt_cancelamento IS NOT NULL THEN 'CANCELADO'
		WHEN dt_pagamento IS NOT NULL THEN 'PAGO'
		ELSE 'PENDENTE'
	END
 ) STORED */
); 

CREATE TABLE Regra_reembolso
( 
  id_evento INT NOT NULL,
  dt_limite DATE NOT NULL,  
  pct_devolvida NUMERIC(8,7) NOT NULL DEFAULT 1.0,  
  
  PRIMARY KEY (id_evento, dt_limite)
);

ALTER TABLE Evento ADD FOREIGN KEY(id_agregado_por) REFERENCES Evento (id);
ALTER TABLE Categoria_inscricao ADD FOREIGN KEY(id_evento) REFERENCES Evento (id);
ALTER TABLE Inscricao ADD FOREIGN KEY(id_categoria) REFERENCES Categoria_inscricao (id);
ALTER TABLE Inscricao ADD FOREIGN KEY(id_pessoa) REFERENCES Pessoa (id);
ALTER TABLE Atividade ADD FOREIGN KEY(id_categoria_inscricao) REFERENCES Categoria_inscricao (id);
ALTER TABLE Pagamento ADD FOREIGN KEY(id_reembolsa) REFERENCES Pagamento (id);
ALTER TABLE Pagamento ADD FOREIGN KEY(id_item_financeiro) REFERENCES Item_financeiro (id);
ALTER TABLE Associacao_a_SBTC ADD FOREIGN KEY(id_pessoa) REFERENCES Pessoa (id);
ALTER TABLE Item_financeiro ADD FOREIGN KEY(id_inscricao) REFERENCES Inscricao (id);
ALTER TABLE Regra_reembolso ADD FOREIGN KEY(id_evento) REFERENCES Evento (id);

/* DROP TABLE IF EXISTS 
    Regra_reembolso,
    Item_financeiro,
    Associacao_a_SBTC,
    Pagamento,
    Atividade,
    Inscricao,
    Categoria_inscricao,
    Evento,
    Pessoa 
CASCADE; */ /* MANTENDO CÓDIGO AQUI APENAS PARA CASO PRECISE MUDAR A MODELAGEM */

